name: global_taxi_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  http: ^1.2.2
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true
  assets:
    - images/onbording1.png
    - images/onbording2.png
    - images/onbording3.png
    - images/splash.png
    - images/icon1.png
    - images/icon4.png
    - images/Icon3.png
    - images/icon2.png
    - images/images1.png
    - images/appple.png
    - images/gg.png
    - images/Welcome Screen.png




